/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nn_runtime_jni;

public class IdsVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IdsVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdsVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nn_runtimeJNI.delete_IdsVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdsVector() {
    this(nn_runtimeJNI.new_IdsVector__SWIG_0(), true);
  }

  public IdsVector(long n) {
    this(nn_runtimeJNI.new_IdsVector__SWIG_1(n), true);
  }

  public long size() {
    return nn_runtimeJNI.IdsVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nn_runtimeJNI.IdsVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nn_runtimeJNI.IdsVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nn_runtimeJNI.IdsVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nn_runtimeJNI.IdsVector_clear(swigCPtr, this);
  }

  public void add(IdVector x) {
    nn_runtimeJNI.IdsVector_add(swigCPtr, this, IdVector.getCPtr(x), x);
  }

  public IdVector get(int i) {
    return new IdVector(nn_runtimeJNI.IdsVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, IdVector val) {
    nn_runtimeJNI.IdsVector_set(swigCPtr, this, i, IdVector.getCPtr(val), val);
  }

}
