/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nn_runtime_jni;

public class IdVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IdVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IdVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nn_runtimeJNI.delete_IdVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdVector() {
    this(nn_runtimeJNI.new_IdVector__SWIG_0(), true);
  }

  public IdVector(long n) {
    this(nn_runtimeJNI.new_IdVector__SWIG_1(n), true);
  }

  public long size() {
    return nn_runtimeJNI.IdVector_size(swigCPtr, this);
  }

  public long capacity() {
    return nn_runtimeJNI.IdVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    nn_runtimeJNI.IdVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return nn_runtimeJNI.IdVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    nn_runtimeJNI.IdVector_clear(swigCPtr, this);
  }

  public void add(long x) {
    nn_runtimeJNI.IdVector_add(swigCPtr, this, x);
  }

  public long get(int i) {
    return nn_runtimeJNI.IdVector_get(swigCPtr, this, i);
  }

  public void set(int i, long val) {
    nn_runtimeJNI.IdVector_set(swigCPtr, this, i, val);
  }

}
