/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nn_runtime_jni;

public class nn_runtime {
  public static long load(String modelPath, boolean normalizeOutputWithSoftmax) {
    return nn_runtimeJNI.load__SWIG_0(modelPath, normalizeOutputWithSoftmax);
  }

  public static long load(String modelPath) {
    return nn_runtimeJNI.load__SWIG_1(modelPath);
  }

  public static DoubleVector predict(long modelHandle, IdsVector idsInputs) {
    return new DoubleVector(nn_runtimeJNI.predict(modelHandle, IdsVector.getCPtr(idsInputs), idsInputs), true);
  }

}
