/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nn_runtime_jni;

public class nn_runtimeJNI {
  public final static native long new_DoubleVector__SWIG_0();
  public final static native long new_DoubleVector__SWIG_1(long jarg1);
  public final static native long DoubleVector_size(long jarg1, DoubleVector jarg1_);
  public final static native long DoubleVector_capacity(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_reserve(long jarg1, DoubleVector jarg1_, long jarg2);
  public final static native boolean DoubleVector_isEmpty(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_clear(long jarg1, DoubleVector jarg1_);
  public final static native void DoubleVector_add(long jarg1, DoubleVector jarg1_, double jarg2);
  public final static native double DoubleVector_get(long jarg1, DoubleVector jarg1_, int jarg2);
  public final static native void DoubleVector_set(long jarg1, DoubleVector jarg1_, int jarg2, double jarg3);
  public final static native void delete_DoubleVector(long jarg1);
  public final static native long new_IdVector__SWIG_0();
  public final static native long new_IdVector__SWIG_1(long jarg1);
  public final static native long IdVector_size(long jarg1, IdVector jarg1_);
  public final static native long IdVector_capacity(long jarg1, IdVector jarg1_);
  public final static native void IdVector_reserve(long jarg1, IdVector jarg1_, long jarg2);
  public final static native boolean IdVector_isEmpty(long jarg1, IdVector jarg1_);
  public final static native void IdVector_clear(long jarg1, IdVector jarg1_);
  public final static native void IdVector_add(long jarg1, IdVector jarg1_, long jarg2);
  public final static native long IdVector_get(long jarg1, IdVector jarg1_, int jarg2);
  public final static native void IdVector_set(long jarg1, IdVector jarg1_, int jarg2, long jarg3);
  public final static native void delete_IdVector(long jarg1);
  public final static native long new_IdsVector__SWIG_0();
  public final static native long new_IdsVector__SWIG_1(long jarg1);
  public final static native long IdsVector_size(long jarg1, IdsVector jarg1_);
  public final static native long IdsVector_capacity(long jarg1, IdsVector jarg1_);
  public final static native void IdsVector_reserve(long jarg1, IdsVector jarg1_, long jarg2);
  public final static native boolean IdsVector_isEmpty(long jarg1, IdsVector jarg1_);
  public final static native void IdsVector_clear(long jarg1, IdsVector jarg1_);
  public final static native void IdsVector_add(long jarg1, IdsVector jarg1_, long jarg2, IdVector jarg2_);
  public final static native long IdsVector_get(long jarg1, IdsVector jarg1_, int jarg2);
  public final static native void IdsVector_set(long jarg1, IdsVector jarg1_, int jarg2, long jarg3, IdVector jarg3_);
  public final static native void delete_IdsVector(long jarg1);
  public final static native long load__SWIG_0(String jarg1, boolean jarg2, boolean jarg3);
  public final static native long load__SWIG_1(String jarg1, boolean jarg2);
  public final static native long load__SWIG_2(String jarg1);
  public final static native long predict(long jarg1, long jarg2, IdsVector jarg2_);
}
